webhook-url: null
logging: false

send:
  messages:
    # Here firt %s is player name and second is message content
    formatting: "`%s`: %s"
    enabled: true
  join:
    # Here %s is player name
    formatting: "**%s joined to the server!**"
    enabled: true
  leave:
    # Here %s is player name
    formatting: "**%s left the server!**"
    enabled: true
  death:
    # Here %s is player name
    formatting: "**%s** died"
    enabled: true
  commands:
    webhook-url: null
    # Here %s is player name, second is command name
    formatting: "`%s` issued **/%s**"
    enabled: false
    ignored-commands:
      - "login"
      - "l"
      - "log"
      - "register"
      - "reg"
      - "r"
  achievements:
    # Here %s is player name, second %s is advancement title
    formatting: "**%s** got `%s` achievement!"
    enabled: true
    locale: en
  server:
    open:
      formatting: "Server open!"
      enabled: true
    shutdown:
      formatting: "Server closed!"
      enabled: true